branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode8.2
before_install:
  - gem install xcpretty -N --no-ri --no-rdoc
  - gem install cocoapods
script:
  - xcodebuild clean -project ShareUtility.xcodeproj -sdk iphonesimulator -target ShareUtility -configuration Debug
  - xcodebuild -project ShareUtility.xcodeproj -sdk iphonesimulator -target ShareUtility -configuration Debug | xcpretty -c
