branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode8.2
#cache:
#  - cocoapods
env:
  matrix:
    - TEST_TYPE=iOS
 #   - TEST_TYPE=macOS
 #   - TEST_TYPE=tvOS
    - TEST_TYPE=CocoaPods
 #   - TEST_TYPE=Carthage
before_install:
- |
  if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] || [ "$TEST_TYPE" = tvOS ]; then
    gem install xcpretty -N --no-ri --no-rdoc
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    gem install cocoapods --pre --quiet --no-ri --no-rdoc
  elif [ "$TEST_TYPE" = Carthage ]; then
    brew update
    brew install carthage || brew upgrade carthage
  fi
script:
  - xcodebuild clean -project ShareUtility.xcodeproj -sdk iphonesimulator -target ShareUtility -configuration Debug
  - xcodebuild -project ShareUtility.xcodeproj -sdk iphonesimulator -target ShareUtility -configuration Debug | xcpretty -c
after_success:
- |
    if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = OSX ] || [ "$TEST_TYPE" = tvOS ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
